### PR TITLE
Fixes broken parsing of git output for LANG=de_DE.UTF-8 (and others).

### PR DESCRIPTION
**Pull request by schiermi**
pulp-puppet-module-builder fails to parse non-english git output:

    > echo $LANG
    de_DE.UTF-8
    > pulp-puppet-module-builder -u git+ssh://…
    cd /root
    git clone --recursive git+ssh://…
    Password: 
    cd idms-puppet
    git status
    git remote show -n origin
    Traceback (most recent call last):
      File "/usr/bin/pulp-puppet-module-builder", line 9, in <module>
        load_entry_point('pulp-puppet-tools==2.6.0', 'console_scripts', 'pulp-puppet-module-builder')()
      File "/usr/lib/python2.7/site-packages/pulp_puppet/tools/puppet_module_builder.py", line 340, in main
        git_checkout(options)
      File "/usr/lib/python2.7/site-packages/pulp_puppet/tools/puppet_module_builder.py", line 204, in     git_checkout
        if not options.origin:
    AttributeError: Values instance has no attribute 'origin'
    >

### CODE REVIEW

**Comment by jortel** [comment]
ok test

**Comment by jortel** [comment]
Thanks for the patch, @schiermi.  The CI script needs to be updated to include the puppet-tools.  I ran the tests manually and found:
```
======================================================================
FAIL: test_shell_failed_no_exit (test.unit.test_puppet_module_builder.TestBuilder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/jortel/git/pulp_puppet/pulp_puppet_tools/test/unit/test_puppet_module_builder.py", line 637, in test_shell_failed_no_exit
    mock_popen.assert_called_with(command.split(), stdout=builder.PIPE, stderr=builder.PIPE)
  File "/usr/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: Popen(['ls', '-Fal'], stderr=-1, stdout=-1)
```
Would you mind updating the test?

**Comment by jortel** [comment]
I would suggest the follow update to the unit test:
```
diff --git a/pulp_puppet_tools/test/unit/test_puppet_module_builder.py b/pulp_puppet_tools/test/unit/test_puppet_module_builder.py
index 5aff960..eb67afe 100644
--- a/pulp_puppet_tools/test/unit/test_puppet_module_builder.py
+++ b/pulp_puppet_tools/test/unit/test_puppet_module_builder.py
@@ -572,8 +572,11 @@ class TestBuilder(TestCase):
 
         self.assertTrue(options.origin is None)
 
+    @patch('os.environ.copy')
     @patch('pulp_puppet.tools.puppet_module_builder.Popen')
-    def test_shell(self, mock_popen):
+    def test_shell(self, mock_popen, mock_copy):
+        env = {'A': 1}
+        mock_copy.return_value = dict(env)
         p = Mock()
         p.wait = Mock(return_value=0)
         p.stdout = Mock()
@@ -587,7 +590,11 @@ class TestBuilder(TestCase):
 
         # validate
 
-        mock_popen.assert_called_with(command.split(), stdout=builder.PIPE, stderr=builder.PIPE)
+        mock_popen.assert_called_with(
+            command.split(),
+            stdout=builder.PIPE,
+            stderr=builder.PIPE,
+            env={'A': 1, 'LC_ALL': 'C'})
 
         self.assertEqual(status, 0)
         self.assertEqual(output, p.stdout.read())
@@ -610,7 +617,6 @@ class TestBuilder(TestCase):
 
         # validate
 
-        mock_popen.assert_called_with(command.split(), stdout=builder.PIPE, stderr=builder.PIPE)
         mock_exit.assert_called_with(1)
 
         self.assertEqual(status, 1)
@@ -634,8 +640,6 @@ class TestBuilder(TestCase):
 
         # validate
 
-        mock_popen.assert_called_with(command.split(), stdout=builder.PIPE, stderr=builder.PIPE)
-
         self.assertEqual(status, 1)
         self.assertEqual(output, '')
         self.assertFalse(mock_exit.called)
```

Thanks!

**Comment by schiermi** [comment]
Thank you very much. I've included your suggestion.

**Comment by mhrivnak** [comment]
ok test

**Pull request merged**
