### PR TITLE
pulp-puppet-module-builder - Errors if no modules with 'Modulefile' or no modules with 'metadata.json' exist in git repo. Will run puppet module build with no path appended.

### PR DESCRIPTION
**Pull request by hjensas**
Bug:
 - 'paths' list can contain empty elements if not modules with both 'Modulefile' and 'metadata.json' files are present in the git repo. 'puppet module build' executed with no appended path, exits with error.
Fix:
 - Remove empty strings from the paths list.

### CODE REVIEW

**Comment by mhrivnak** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by mhrivnak** [comment]
https://pulp.plan.io/issues/1379

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok to test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by rbarlow** [comment]
@hjensas Thank you for the pull request! We aren't maintaining our 2.6 release anymore since we have now released 2.7, so I am going to close this. Can you reopen your branch against our 2.7-dev branch?

Additionally, can you add a unit test or two to test that this code solves the issue? The tests for this module are located here:

https://github.com/pulp/pulp_puppet/blob/master/pulp_puppet_tools/test/unit/test_puppet_module_builder.py

**Pull request closed without merging**
