### PR TITLE
Issue 662: Minor Fix in documentation

### PR DESCRIPTION
**Pull request by shubham90**
Changes done in pulp, pulp_rpm, pulp_puppet.

### CODE REVIEW

**Comment by ipanova** [comment]
@shubham90  don't forget to do the same for pulp_rpm

**Comment by shubham90** [comment]
@ipanova Done! Thanks..

**Comment by rbarlow** [comment]
@shubham90 I noticed that you are making this pull request from your master branch. It will be difficult to open many simultaneous pull requests if you make your PRs from your master. I suggest in the future that you make each pull request from its own branch in your repository. This way, you can have (ideally) one commit per pull request.

**Comment by rbarlow** [comment]
I noticed after merging the above that your commit message was missing the reference to the bug in the format that Redmine looks for. Next time, add a line at the end of your commit message like this:

```
fixes #662
```

If you do that, the Redmine ticket will get a neat little reference to your commit on it automatically. No need to worry about going back and fixing this, just a note for next time.

**Pull request merged**
